<?php

namespace App\Views;

use Core\View;

class NavBar extends View
{

    protected $data = [
        'attr' => [
            'class' => 'navbar',
        ],
        'logo' => [
            'attr' => [
                'class' => 'logo',
                'href' => 'index.php',
            ],
        ],
//    'toggler' => [
//        'attr' => [
//            'class' => 'toggler-botton',
//            'type' => 'button',
//            'data-toggle' => 'collapse',
//            'data-target' => '#navbarToggler'
//        ],
//    ],
//    'toggler-icon' => [
//        'attr' => [
//            'class' => 'toggler-icon',
//        ],
//    ],
        'nav-items-container' => [
            'attr' => [
                'class' => 'nav-items-container',
                'id' => 'navbarToggler',
            ],
        ],
        'nav-items' => [
            'attr' => [
                'class' => 'nav-items',
            ],
        ],
        'nav-item-array' => [
            'Register' => [
                'attr' => [
                    'class' => 'nav-item',
                ],
                'nav-link' => [
                    'attr' => [
                        'class' => 'nav-link',
                        'href' => 'register.php',
                    ],
                ],

            ],
            'Login' => [
                'attr' => [
                    'class' => 'nav-item',
                ],
                'nav-link' => [
                    'attr' => [
                        'class' => 'nav-link',
                        'href' => 'login.php',
                    ],
                ],
            ],
            'Logout' => [
                'attr' => [
                    'class' => 'nav-item',
                ],
                'nav-link' => [
                    'attr' => [
                        'class' => 'nav-link',
                        'href' => 'Logout.php',
                    ],
                ],
            ],
            'Home' => [
                'attr' => [
                    'class' => 'nav-item',
                ],
                'nav-link' => [
                    'attr' => [
                        'class' => 'nav-link',
                        'href' => 'Index.php',
                    ],
                ],
            ],
            'Drinks' => [
                'attr' => [
                    'class' => 'nav-item',
                ],
                'nav-link' => [
                    'attr' => [
                        'class' => 'nav-link',
                        'href' => 'Drinks.php',
                    ],
                ],
            ],
        ],

        'form' => [
            'attr' => [
                'class' => 'nav-form',
            ],
            'field' => [
                'attr' => [
                    'class' => 'nav-form-input',
                    'type' => 'search',
                    'placeholder' => 'Search',
                ],
            ],
            'buttons' => [
                'search' => [
                    'attr' => [
                        'class' => 'nav-form-button',
                        'type' => 'submit',
                    ],
                ],
            ],
        ],

    ];


    public function __construct()
    {
        parent::__construct($this->data);
        $this->disableCurrentPage();
    }


    private function disableCurrentPage()
    {
        foreach ($this->data['nav-item-array'] as &$value) {
            if ($value['nav-link']['attr']['href'] === basename($_SERVER['PHP_SELF'])) {
                $value['nav-link']['attr']['class'] .= ' disabled';
            }
        }

    }


    public function render($templatePath = '')
    {
        return parent::render('../core/templates/navbar.tpl.php'); // TODO: Change the autogenerated stub

    }
}